
import type { Post, Thread, Capsule } from "./types";

export const MOCK_POSTS: Post[] = [
    {
        id: "1",
        user: {
            id: "u1",
            name: "NP Photography Club",
            avatar: "https://images.unsplash.com/photo-1542596594-649edbc13630?q=80&w=200&auto=format&fit=crop",
            role: "Student",
        },
        type: "image",
        mediaUrl: "https://www.np.edu.sg/images/default-source/about-np-2/facilities/atrium.jpg?sfvrsn=57267937_2?q=80&w=800&auto=format&fit=crop",
        content: "Golden hour at the Atrium! 🌅 Who remembers rushing purely for the free popcorn? #NgeeAnnPoly #CampusLife #Sunset",
        likes: 245,
        comments: [],
        timestamp: "2 hours ago",
        date: "2024-05-20",
        category: "Campus Life",
        location: "The Atrium",
    },
    {
        id: "2",
        user: {
            id: "u2",
            name: "Jamie Lim",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jamie",
            role: "Alumni",
        },
        type: "image",
        mediaUrl: "https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=800&auto=format&fit=crop",
        content: "Found this old gem from 2018! The old Makan Place layout was superior, fight me. 😤🍲 #Throwback #MakanPlace #Alumni",
        likes: 89,
        comments: [
            {
                id: "c1",
                user: { id: "u3", name: "Alex Tan", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex", role: "Alumni" },
                content: "Facts! The western stall was legendary.",
                timestamp: "1 hour ago"
            }
        ],
        timestamp: "5 hours ago",
        date: "2024-05-20", // Posted today, but referring to 2018
        category: "Throwback",
        location: "Makan Place",
    },
    {
        id: "3",
        user: {
            id: "u4",
            name: "Red Camp 24",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=RedCamp",
            role: "Student",
        },
        type: "image",
        mediaUrl: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?q=80&w=800&auto=format&fit=crop",
        content: "READY FOR RED CAMP?! 🔥 The fierce spirit of the lions is awake! See you freshmen soon! ❤️🦁 #RedCamp #NgeeAnnPoly",
        likes: 512,
        comments: [],
        timestamp: "1 day ago",
        date: "2024-05-19",
        category: "Events",
        location: "Convention Centre",
    },
    {
        id: "4",
        user: {
            id: "u5",
            name: "Library Whisperer",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lib",
            role: "Student",
        },
        type: "image",
        mediaUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=800&auto=format&fit=crop",
        content: "Late night grinding at Lien Ying Chow Library. The silence is loud tonight. 📚☕ #FinalsSzn #StudyHard",
        likes: 120,
        comments: [],
        timestamp: "2 days ago",
        date: "2024-05-18",
        category: "Academic",
        location: "Lien Ying Chow Library",
    },
    {
        id: "5",
        user: {
            id: "u6",
            name: "Poly Arts",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arts",
            role: "Student",
        },
        type: "image",
        mediaUrl: "https://slcedu.sg/wp-content/uploads/2024/08/AboutNgeeAnn.webp?q=80&w=800&auto=format&fit=crop",
        content: "Our annual Arts Fiesta is coming soon! Get ready for a week of performances and exhibitions. 🎭🎨 #ArtsFiesta #NPArts",
        likes: 340,
        comments: [],
        timestamp: "3 days ago",
        date: "2024-05-17",
        category: "Arts",
        location: "Arts Centre",
    },
    {
        id: "6",
        user: {
            id: "u7",
            name: "Ngee Ann Poly",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=NP",
            role: "Staff",
        },
        type: "image",
        mediaUrl: "https://slcedu.sg/wp-content/uploads/2024/08/AboutNgeeAnn.webp?q=80&w=800&auto=format&fit=crop",
        content: "Welcome back to school! Let's make this semester count. 💪 #NgeeAnnPoly #BackToSchool",
        likes: 1000,
        comments: [],
        timestamp: "1 week ago",
        date: "2024-05-13",
        category: "Campus Life",
        location: "Main Gate",
    },
    {
        id: "7",
        user: { id: "u8", name: "Film Society", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Film", role: "Student" },
        type: "image",
        mediaUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=800&auto=format&fit=crop",
        content: "Outdoor movie screening was a blast! 🎬 popcorn + stars + friends = perfect night. #FilmSoc #MovieNight",
        likes: 156,
        comments: [],
        timestamp: "2 weeks ago",
        date: "2024-05-01",
        category: "Events",
        location: "Sports Complex Field",
    },
    {
        id: "8",
        user: { id: "u9", name: "Engineering Fam", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Eng", role: "Student" },
        type: "image",
        mediaUrl: "https://slcedu.sg/wp-content/uploads/2024/08/AboutNgeeAnn.webp?q=80&w=800&auto=format&fit=crop",
        content: "Final Year Project submission done! 🛠️ It's been a long journey but we made it. Thanks block 37 for being our second home.",
        likes: 312,
        comments: [],
        timestamp: "1 month ago",
        date: "2024-04-15",
        category: "Academic",
        location: "Block 37",
    },
    {
        id: "9",
        user: { id: "u10", name: "Foodie Club", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Foodie", role: "Student" },
        type: "image",
        mediaUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=800&auto=format&fit=crop",
        content: "Munch's new menu items are 🔥. Highly recommend the truffle fries!",
        likes: 201,
        comments: [],
        timestamp: "3 days ago",
        date: "2024-05-19",
        category: "Campus Life",
        location: "Munch",
    },
    {
        id: "10",
        user: { id: "u11", name: "BA Society", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=BA", role: "Student" },
        type: "image",
        mediaUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=800&auto=format&fit=crop",
        content: "Business Studies orientation group photo! Welcome to the fam freshies! 💼👔",
        likes: 420,
        comments: [],
        timestamp: "1 month ago",
        date: "2024-04-10",
        category: "Events",
        location: "Block 72",
    },
    {
        id: "11",
        user: { id: "u12", name: "Alumni Relations", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alumni", role: "Staff" },
        type: "image",
        mediaUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=800&auto=format&fit=crop",
        content: "Class of 2010 reunion! So good to see everyone back on campus. #NPAlumni #Homecoming",
        likes: 567,
        comments: [],
        timestamp: "2 months ago",
        date: "2024-03-20",
        category: "Throwback",
        location: "Alumni House",
    },
    {
        id: "12",
        user: { id: "u13", name: "Street Dance", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dance", role: "Student" },
        type: "image",
        mediaUrl: "https://slcedu.sg/wp-content/uploads/2024/08/AboutNgeeAnn.webp?q=80&w=800&auto=format&fit=crop",
        content: "Practicing for the big show. Blood, sweat, and tears. Let's go NR! 💃🕺",
        likes: 289,
        comments: [],
        timestamp: "5 days ago",
        date: "2024-05-18",
        category: "Arts",
        location: "OurSpace",
    }
];

export const MOCK_THREADS: Thread[] = [
    {
        id: "t1",
        title: "Best study spots with power plugs?",
        content: "I'm looking for a quiet place to study that has accessible power plugs. The library is always full! Any hidden gems?",
        author: { id: "u6", name: "SleepyStudent", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sleepy", role: "Student" },
        category: "Academic",
        upvotes: 45,
        commentCount: 12,
        timestamp: "3 hours ago"
    },
    {
        id: "t2",
        title: "Lost AirPods Case at Block 51",
        content: "Hi everyone, I lost my AirPods case (with a Pikachu cover) at Block 51 L4 lecture theatre. Please DM if found!",
        author: { id: "u7", name: "ClumsyOne", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Clumsy", role: "Student" },
        category: "Lost & Found",
        upvotes: 120,
        commentCount: 3,
        timestamp: "6 hours ago"
    },
    {
        id: "t3",
        title: "Confession: I actually miss HBL",
        content: "Unpopular opinion but waking up 5 mins before class was a vibe. Commuting takes so much energy 😭",
        author: { id: "u8", name: "Anon123", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anon", role: "Alumni" },
        category: "Confessions",
        upvotes: 890,
        commentCount: 56,
        timestamp: "1 day ago"
    }
];

export const MOCK_CAPSULES: Capsule[] = [
    {
        id: "c1",
        title: "My Freshman Hopes",
        description: "A letter to my future self about what I hope to achieve in NP.",
        unlockDate: "2026-04-15",
        createdAt: "2023-04-15",
        isLocked: true,
        coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop"
    },
    {
        id: "c2",
        title: "First Day of Y3",
        description: "Photos and thoughts from the start of my final year.",
        unlockDate: "2023-12-01",
        createdAt: "2023-04-16",
        isLocked: false,
        coverImage: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=800&auto=format&fit=crop",
        content: "Today was actually pretty fun! Met up with the gang at Munch. Can't believe it's the last year already."
    },
    {
        id: "c3",
        title: "Graduation Goals",
        description: "Notes on where I want to be when I graduate.",
        unlockDate: "2027-04-20",
        createdAt: "2024-01-10",
        isLocked: true,
        coverImage: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?q=80&w=800&auto=format&fit=crop",
        email: "student@example.com"
    },
    {
        id: "c4",
        title: "CCA Farewell",
        description: "Last day of training with the team.",
        unlockDate: "2023-11-15",
        createdAt: "2023-11-01",
        isLocked: false,
        coverImage: "https://www.np.edu.sg/images/default-source/student-life/clubs-societies/arts-cultural/english-drama.jpg?sfvrsn=5ea4583f_2?q=80&w=800&auto=format&fit=crop",
        content: "Gonna miss these guys so much! 😭",
        mediaUrl: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=800&auto=format&fit=crop",
        mediaType: "image",
    }
];
